-- 출처: https://programmers.co.kr/learn/courses/30/lessons/59042
-- 문제: 없어진 기록 찾기

SELECT A_OUT.ANIMAL_ID, A_OUT.NAME
FROM ANIMAL_OUTS AS A_OUT
LEFT JOIN ANIMAL_INS AS A_INS
ON A_OUT.ANIMAL_ID = A_INS.ANIMAL_ID
WHERE A_INS.DATETIME IS NULL
ORDER BY A_OUT.ANIMAL_ID
