-- 출처: https://programmers.co.kr/learn/courses/30/lessons/59045
-- 문제: 보호소에서 중성화한 동물

SELECT A_IN.ANIMAL_ID, A_IN.ANIMAL_TYPE, A_IN.NAME
FROM ANIMAL_INS AS A_IN LEFT JOIN ANIMAL_OUTS AS A_OUT
ON A_IN.ANIMAL_ID = A_OUT.ANIMAL_ID
WHERE SUBSTRING_INDEX(SEX_UPON_INTAKE, ' ', 1) = 'intact'
AND SEX_UPON_INTAKE != SEX_UPON_OUTCOME
ORDER BY A_IN.ANIMAL_ID;